#!/bin/bash

DEBUG='\033[1;30m'
NC='\033[0m'

################################################################################
# Welcome Banner

printf "\n\n"
printf "Generating Can-Swe\n"
printf "==================\n"

################################################################################
# Docker

# Detect docker socket running
docker=$(curl -s --unix-socket /var/run/docker.sock http://ping > /dev/null)
status=$?
if [ "$status" == "7" ]; then
  printf "Docker is not running\n"
  printf "Please start docker and try again\n"
  exit
fi

# Stop running containers
container=$(docker stop canswe &> /dev/null)
status=$?
if [ "$status" == "0" ]; then  # container was running
  printf "Old Can-Swe container stopped\n"
fi

# Look for image & build image
image=$(docker image inspect canswe &> /dev/null)
status=$?
if [ "$status" == "1" ]; then # no image found
  printf "Building Can-Swe image, please wait...\n"
  printf "${DEBUG}"
  docker build -t canswe .
  printf "${NC}"
fi

# Start up the container
printf "Starting new Can-Swe container\n"
container=$(docker run -d --rm -v $(pwd)/src:/opt/src -v $(pwd)/dist:/opt/dist -e JEKYLL_ENV=production canswe sh build_production)
