#!/bin/bash

WEB=$(lsof -i :3000 | awk 'FNR > 1 {print $2}')
WEBUI=$(lsof -i :3001 | awk 'FNR > 1 {print $2}')

docker stop $(docker ps -aq);

if [ ! -z "${WEB}" ]; then
  kill -2|INT $WEB
fi

if [ ! -z "${WEBUI}" ]; then
  kill -2|INT $WEBUI
fi

docker-compose up --build
