#!/bin/bash

# Install node modules
if [ ! -d ./node_modules ]; then
  echo 'Installing Node Modules...'
  yarn
fi

# Remove any of our existing container
if [ ! -z $(docker ps -q) ]; then
  echo 'Removing old containers...'
  docker rm $(docker stop $(docker ps -q --filter ancestor=canswe_jekyll))
fi

# kill anything using 3000
WEB=$(lsof -i :3000 | awk 'FNR > 1 {print $2}')
if [ ! -z "${WEB}" ]; then
  echo 'Stoping long running browsersync...'
  kill -2|INT $WEB
fi

# kill anything using 3001
WEBUI=$(lsof -i :3001 | awk 'FNR > 1 {print $2}')
if [ ! -z "${WEBUI}" ]; then
  echo 'Stopping long running browsersync config...'
  kill -2|INT $WEBUI
fi

# Create build css directory
if [ ! -d ./dist/assets/css ]; then
  echo 'Creating build CSS directory...'
  mkdir -p ./dist/assets/css
  yarn build:css
fi

# Create build JS directory
if [ ! -d ./dist/assets/js ]; then
  echo 'Creating build js directory...'
  mkdir -p ./dist/assets/js
  yarn build:js
fi

# Run the processes, but trap them to kill easier
trap 'kill %1; kill %2; kill %3' SIGINT
yarn dev:css & yarn dev:js & yarn dev:browsersync & docker-compose up
