FROM alpine:latest
MAINTAINER Gregory Daynes <gregdaynes@gmail.com>

# Build tooling

RUN apk upgrade --update \
 && apk add build-base \
 && apk add git \
 && apk add zlib libxml2 libxml2-dev \
 && apk add ruby ruby-dev ruby-bundler ruby-json

# Gems, Jekyll & Plugins

RUN gem install --no-document rdoc \
 && gem install --no-document jekyll \
 && gem install --no-document bundler

WORKDIR /opt

EXPOSE 4000
CMD jekyll --version
