-
  category: Safety Pants
  sku: P001
  name: POLY PRO 3600
  description: The P001 POLY PRO 3600 is the industry standard for comercial and recreational sawyers, and is the favorite amoung consumers. This all season pant is light weight and breathable with excellent range of motion.
  specs:
    - Meets WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 100% Polyester Outer Shell
    - Fabric is Heavy Double Knit 13oz for added durability
    - Knit provides excellent ventilation and movement
    - Light weight at 2.2lb/992 g (size 34-36)
    - Nylon reinforced crotch with extra bar tacking
    - hip pockets are ergonomically located to prevent hang ups during cutting and bending
    - Signature pocket flaps keep chips out and allow quick easy access
    - Waist sizing: 28-30, 30-32, 34-36, 38-40, 42-44
    - 'Inseam length: 30"'
  application:
    - All season Snowflake/Sun/Raindrop
    - Safety +
    - Cost $

-
  category: Safety Pants
  sku: P001B
  name: POLY PRO BACKPAD 3600
  description: The P001B POLY PRO BACKPAD 3600 offers all of the user benfits of the P001 Poly Pro with the added protection of ankle to knee safety pad wrapping around the calf.
  specs:
    - Exceeds WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 100% Polyester Outer Shell
    - Fabric is Heavy Double Knit 13oz for added durability
    - Knit provides excellent ventilation and movement
    - Full wrap protection extends around the calf
    - Light weight at 2.4lb/1105g (size 34-36)
    - Nylon reinforced crotch with extra bar tacking
    - hip pockets are ergonomically located to prevent hang ups during cutting and bending
    - Signature pocket flaps keep chips out and allow quick easy access
    - Waist sizing: 28-30, 30-32, 34-36, 38-40, 42-44
    - 'Inseam length: 30"'
  application:
    - All season Snowflake/Sun/Raindrop
    - Safety ++
    - Cost $$

-
  category: Safety Pants
  sku: P002
  name: DENIM PRO
  description: The time honoured P002 DENIM PRO 3600 would make your Grandad proud. Rugged 14oz denim is very durable and wears like a work jean. All the benefits of 100% cotton, break these in and you wont look back.
  specs:
    - Meets WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 100% Denim Outer Shell
    - 14oz Denim is rugged and very durable, break these in and never look back
    - Light weight at 2.8lb/1304g (size 34-36)
    - Nylon reinforced crotch with extra bar tacking
    - hip pockets are ergonomically located to prevent hang ups during cutting and bending
    - Signature pocket flaps keep chips out and allow quick easy access
    - Waist sizing: 28-30, 30-32, 34-36, 38-40, 42-44
    - 'Inseam length: 30"'
  application:
    - Snowflake/Sun
    - Safety +
    - Cost $

-
  category: Safety Pants
  sku: P003
  name: NYLON PRO
  description: The P003 NYLON PRO 3600 is your best friend through the cold, wet, soggy, snowy fall winter spring of the Pacific North West. Made with the same polyurethane backed 420 denier nylon from our rainwear, these pants provide excellent moisture protection.
  specs:
    - Meets WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 100% Nylon Outer Shell
    - 420 Denier Nylon is super strong
    - The same nylon used in our rain wear for excellent moisture protection
    - Light weight at 2.2lb/992g (size 34-36)
    - Nylon reinforced crotch with extra bar tacking
    - hip pockets are ergonomically located to prevent hang ups during cutting and bending
    - Signature pocket flaps keep chips out and allow quick easy access
    - Waist sizing: 28-30, 30-32, 34-36, 38-40, 42-44
    - 'Inseam length: 30"'
  application:
    - Snowflake/Raindrop
    - Safety +
    - Cost $

-
  category: Safety Pants
  sku: P004
  name: NYLON / POLY PRO
  description: If you are looking for some ventilation in the Nylon Pro we can meet half way with the NYLON / POLY PRO 3600. Dubbed the "Half Half" this pant keeps the snow and rain off the front and lets the heat out the back.
  specs:
    - Meets WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 50% Nylon 50% Polyester Outer Shell
    - The same 420 Denier Nylon used in our rain wear for excellent strength moisture protection
    - The polyester back allows for great ventilation
    - Light weight at 2.2lb / 992g (size 34-36)
    - Nylon reinforced crotch with extra bar tacking
    - hip pockets are ergonomically located to prevent hang ups during cutting and bending
    - Signature pocket flaps keep chips out and allow quick easy access
    - Waist sizing: 28-30, 30-32, 34-36, 38-40, 42-44
    - 'Inseam length: 30"'
  application:
    - All season Snowflake/Sun/Raindrop
    - Safety +
    - Cost $

-
  category: Safety Pants
  sku: P005
  name: DRILL COTTON PRO
  description: The P005 DRILL COTTON PRO 3600 is a welcome addtion for the warm season. 100% cotton wicks moisture and provides great ventilation for cool comfortable protection.
  specs:
    - Meets WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 100% Drill Cotton outer shell
    - Light weight at 2.4lb / 1105g (size 34-36)
    - Nylon reinforced crotch with extra bar tacking
    - hip pockets are ergonomically located to prevent hang ups during cutting and bending
    - Signature pocket flaps keep chips out and allow quick easy access
    - Waist sizing: 28-30, 30-32, 34-36, 38-40, 42-44
    - 'Inseam length: 30"'
  application:
    - Snowflake/Sun
    - Safety +
    - Cost $
-
  category: Chaps & Workwear
  sku: P008
  name: CHAP PRO (3 Buckles)
  description: Easy on Easy off the P008 CHAP PRO 3600 is great for intermittant use. If you are a commercial faller or out gathering firewood for the winter, these will help get you home.
  specs:
    - Meets WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 100% 420 Denier Nylon shell
    - Light weight at 2.1lb / 963g (size 34-36)
    - 'Adjustable waist strap with 2" moster buckle'
    - 'Three 1" quick release buckles in back'
  application:
    - All season Snowflake/Sun/Raindrop
    - Safety +
    - Cost $

-
  category: Chaps & Workwear
  sku: P008B
  name: CHAP PRO BP (Zipper Back)
  description: The P008B CHAP PRO BACKPAD 3600 Provides added protection and
  specs:
    - Meets WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 100% 420 Denier Nylon shell
    - Light weight at 2.5lb / 1162g (size 34-36)
    - 'Adjustable waist strap with 2" moster buckle'
    - '18" zippered back'
    - Full wrap safety pad wraps around calf from ankle to knee.
  application:
    - All season Snowflake/Sun/Raindrop
    - Safety ++
    - Cost $

-
  category: Safety Pants
  sku: P009
  name: RIGGER PRO
  description: The RIGGER PRO 3600 is made with a woven 600 denier polyester front and our classic polester knit back. The pant is made for longevity. The woven poly front can handle extreme abrasion and has excellent resistance to oil and gas.
  specs:
    - Meets WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 50% Woven 600 Denier Polyester front
    - 50% polyester knit back
    - Light weight at 2.2lb / 992g (size 34-36)
    - Nylon reinforced crotch with extra bar tacking
    - hip pockets are ergonomically located to prevent hang ups during cutting and bending
    - Signature pocket flaps keep chips out and allow quick easy access
    - Waist sizing: 28-30, 30-32, 34-36, 38-40, 42-44
    - 'Inseam length: 30"'
  application:
    - All season Snowflake/Sun/Raindrop
    - Safety +
    - Cost $$

-
  category: Safety Pants
  sku: M001
  name: POLY PROMAX
  description: The Poly PROMAX is an all season pant that is light weight and breathable with excellent range of motion. The same design as our popular POLY PRO with added protection of 4100 TCS protective pad.
  specs:
    - Exceeds WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 50% Woven 600 Denier Polyester front
    - 50% polyester knit back
    - Light weight at 2.6lb / 1190g (size 34-36)
    - Nylon reinforced crotch with extra bar tacking
    - hip pockets are ergonomically located to prevent hang ups during cutting and bending
    - Signature pocket flaps keep chips out and allow quick easy access
    - Waist sizing: 28-30, 30-32, 34-36, 38-40, 42-44
    - 'Inseam length: 30"'
  application:
    - All season Snowflake/Sun/Raindrop
    - Safety ++
    - Cost $$

-
  category: Safety Pants
  sku: M002
  name: SEISMIC PROMAX
  description: The SEISMIC PRO covers all the bases. The rugged durability of the Rigger Pro with 4100 TCS protection and full wrap backpad. This product was design inconjuntion with indusry professionals for seismic slashing in the oil and gas industry. Top of line function and protection.
  specs:
    - Exceeds WCB PPE 1-1997 Threshold Chains Speed (TCS) 3600
    - 50% Woven 600 Denier Polyester front
    - 50% polyester knit back
    - Light weight at 3lb / 1360g (size 34-36)
    - Nylon reinforced crotch with extra bar tacking
    - Full wrap protection extends around the calf
    - Belt Loops
    - hip pockets are ergonomically located to prevent hang ups during cutting and bending
    - Signature pocket flaps keep chips out and allow quick easy access
    - Waist sizing: 28-30, 30-32, 34-36, 38-40, 42-44
    - 'Inseam length: 30"'
  application:
    - All season Snowflake/Sun/Raindrop
    - Safety +++
    - Cost $$$

-

  category: Rainwear
  sku: RW011C
  name: HURRICANE JACKET
  description: This HURRICANE CLASSIC jackets reputation lives up to its name. The toughest product on the market with 420 Dienier Nylon outer shell and 210 Denier nylon shell, Both polyurethan coated. Lining and shell are sewn "coating to coating" to reduce abrasive damage to coating and improve lopngevity. The soft finish provides added comfort, inside and out.
  specs:
    - Outer material made with 420 Denier polyurethane coated nylon
    - Liner materials made with 210 denier polyurethane coated nylon
    - Double lined sleeves, shoulder and upper torso.
    - Cape design allows for venting and mid torso
    - well sealed breast pocket
    - nickel plated quick snaps
    - 3M retro reflective trim at midpoint
    - Velcro cuffs to keep sleeves in position

-

  category: Rainwear
  sku: RW011L
  name: HURRICANE JACKET (Fleece Lined)
  description: All the benefits of the Hurricane Classic with the added warmth of a polar feece lining.
  specs:
    - Outer material made with 420 Denier polyurethane coated nylon
    - Liner materials made with 210 denier polyurethane coated nylon
    - Polar fleece lining for added warmth
    - Double lined sleeves, shoulder and upper torso.
    - Cape design allows for venting and mid torso
    - well sealed breast pocket
    - nickel plated quick snaps
    - 3M retro reflective trim at midpoint
    - Velcro cuffs to keep sleeves in position

-

  category: Rainwear
  sku: RW012
  name: HURRICANE BIBPANTS (Red)
  description: The HURRICAN CLASSIC bib pants pair perfectly with the jacket as the toughest product on the market. 420 Dienier Nylon outer shell and 210 Denier nylon shell, Both polyurethan coated. Lining and shell are sewn "coating to coating" to reduce abrasive damage to coating and improve lopngevity. The soft finish provides added comfort, inside and out. Wide leg design allows for "boots on" access
  specs:
    - Outer material made with 420 Denier polyurethane coated nylon
    - Liner materials made with 210 denier polyurethane coated nylon
    - Double lined thoughout
    - Heavy elastic shoiulder straps with nylon adjustable clips
    - wide leg for easy over the boot donning and doffing

-

  category: Rainwear
  sku: RW013
  name: HURRICANE HOOD (Unlined)
  description: Hoods and hardhats don’t always mix, that is why our hoods are removable. Avalable by request can be applied to any jacket.
  specs:
    - 420 denier polyurethane coated nylon inside and out
    - draw string
    - nickel plated quick snaps

-

  category: Rainwear
  sku: RW013L
  name: HURRICANE HOOD (Fleece Lined)
  description: Hoods and hardhats don’t always mix, that is why our hoods are removable. Avalable by request can be applied to any jacket.
  specs:
    - 420 denier polyurethane coated nylon inside and out
    - draw string
    - nickel plated quick snaps
    - Polar fleece lined


-

  category: Rainwear
  sku: RW014
  name: HURRICANE HIGH VIS JACKET
  description: Design to meet WCB PPE 2 this jacket offer all the great benefits of the HURRICANE CLASSIC with added protection of fluerecent yellow colouring and high vis markings. Meeting the requirements of type 1, 2 and 3 garments this jacket will keep you visible in all conditions
  specs:
    - Outer material made with 400 Denier polyurethane coated Polyester
    - Liner materials made with 210 denier polyurethane coated nylon
    - Double lined sleeves, shoulder and upper torso.
    - Cape design allows for venting and mid torso
    - well sealed breast pocket
    - nickel plated quick snaps
    - 3M retro reflective trim at midpoint
    - Velcro cuffs to keep sleeves in position

-
  category: Rainwear
  sku: RW014
  name: HURRICANE HIGH VIS JACKET
  description: Design to meet WCB PPE 2 this jacket offer all the great benefits of the HURRICANE CLASSIC with added protection of fluerecent yellow colouring and high vis markings. Meeting the requirements of type 1, 2 and 3 garments this jacket will keep you visible in all conditions
  specs:
    - Outer material made with 400 Denier polyurethane coated Polyester
    - Liner materials made with 210 denier polyurethane coated nylon
    - Double lined sleeves, shoulder and upper torso.
    - Cape design allows for venting and mid torso
    - well sealed breast pocket
    - nickel plated quick snaps
    - 3M retro reflective trim at midpoint
    - Velcro cuffs to keep sleeves in position

-
  category: Rainwear
  sku: Y003S
  name: 1STAID POUCH (Small)
  description: resilient little pouch to cary tensor, gauze or other first aid necessities. Slides nicely onto a belt of suspenders
  specs:
    - 400 Denier Nylon
    - nickle plated quick snap
    - large loop in back

-
  category: Rainwear
  sku: Y003L
  name: FANNY POUCH (Large)
  description: if you need a little extra storage this easily slide onto your belt or suspenders
  specs:
    - 400 Denier Nylon
    - nickle plated quick snaps
    - large loop in back

